import { Timestamp } from "firebase/firestore";

/**
 * Learning System Types
 * These types are for the new in-platform learning system.
 * All data is stored in NEW collections, no modifications to existing collections.
 */

// ==================== SUBJECT TYPES ====================

/**
 * A learning subject corresponds to a skill (e.g., "React", "Node.js")
 * Cached data includes roadmap generated by AI
 */
export interface LearningSubject {
  id: string;
  subjectName: string; // Normalized skill name (e.g., "React", "Node.js")
  displayName: string; // Display-friendly name
  description: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  estimatedHours: number;
  prerequisites: string[];
  // AI-generated roadmap (cached in this document)
  roadmap?: string;
  roadmapGeneratedAt?: Timestamp;
  // Chapters metadata
  chaptersGenerated: boolean;
  chapterCount: number;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

/**
 * Input for creating a new subject
 */
export type CreateSubjectInput = Omit<
  LearningSubject,
  "id" | "roadmap" | "roadmapGeneratedAt" | "chaptersGenerated" | "chapterCount" | "createdAt" | "updatedAt"
>;

// ==================== CHAPTER TYPES ====================

/**
 * A chapter within a subject
 * Contains cached AI-generated content (overview, concepts, notes)
 */
export interface LearningChapter {
  id: string;
  subjectId: string;
  subjectName: string; // Denormalized for easy display
  chapterNumber: number;
  title: string;
  description: string;
  estimatedMinutes: number;
  // AI-generated content (cached in this document)
  overview?: string;
  overviewGeneratedAt?: Timestamp;
  concepts?: string[];
  conceptsGeneratedAt?: Timestamp;
  aiNotes?: string;
  aiNotesGeneratedAt?: Timestamp;
  // YouTube videos (cached in this document)
  videos?: YouTubeVideo[];
  videosGeneratedAt?: Timestamp;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

/**
 * YouTube video resource
 */
export interface YouTubeVideo {
  videoId: string;
  title: string;
  description: string;
  thumbnailUrl: string;
  channelTitle: string;
  publishedAt: string;
  duration?: string;
  viewCount?: string;
}

/**
 * Input for creating a new chapter
 */
export type CreateChapterInput = Omit<
  LearningChapter,
  | "id"
  | "overview"
  | "overviewGeneratedAt"
  | "concepts"
  | "conceptsGeneratedAt"
  | "aiNotes"
  | "aiNotesGeneratedAt"
  | "videos"
  | "videosGeneratedAt"
  | "createdAt"
  | "updatedAt"
>;

// ==================== PROGRESS TYPES ====================

/**
 * Student's progress on a learning subject
 */
export interface LearningSubjectProgress {
  id: string;
  studentId: string;
  subjectId: string;
  subjectName: string; // Denormalized for easy display
  completedChapters: string[]; // Array of chapter IDs
  notesViewedChapters: string[]; // Chapters where user viewed AI notes
  videosViewedChapters: string[]; // Chapters where user viewed videos
  progressPercentage: number;
  startedAt: Timestamp;
  lastAccessedAt: Timestamp;
  completedAt?: Timestamp;
}

/**
 * Input for creating/updating progress
 */
export type CreateProgressInput = Omit<
  LearningSubjectProgress,
  "id" | "progressPercentage" | "completedAt" | "createdAt" | "updatedAt"
>;

// ==================== API RESPONSE TYPES ====================

/**
 * Response when generating subject roadmap
 */
export interface GenerateRoadmapResponse {
  success: boolean;
  subject: LearningSubject;
  cached: boolean;
  error?: string;
}

/**
 * Response when generating chapters
 */
export interface GenerateChaptersResponse {
  success: boolean;
  chapters: LearningChapter[];
  cached: boolean;
  error?: string;
}

/**
 * Response when generating chapter overview/concepts
 */
export interface GenerateChapterContentResponse {
  success: boolean;
  chapter: LearningChapter;
  cached: boolean;
  error?: string;
}

/**
 * Response when generating AI notes
 */
export interface GenerateNotesResponse {
  success: boolean;
  notes: string;
  cached: boolean;
  error?: string;
}

/**
 * Response when fetching videos
 */
export interface FetchVideosResponse {
  success: boolean;
  videos: YouTubeVideo[];
  cached: boolean;
  error?: string;
}

// ==================== AI GENERATION TYPES ====================

/**
 * AI-generated roadmap structure
 */
export interface AIRoadmap {
  overview: string;
  learningPath: string[];
  tips: string[];
  estimatedTotalHours: number;
}

/**
 * AI-generated chapter structure (from roadmap generation)
 */
export interface AIChapterOutline {
  chapterNumber: number;
  title: string;
  description: string;
  estimatedMinutes: number;
  keyTopics: string[];
}

/**
 * Full AI roadmap response
 */
export interface AIRoadmapResponse {
  roadmap: AIRoadmap;
  chapters: AIChapterOutline[];
}

/**
 * AI-generated chapter overview
 */
export interface AIChapterOverview {
  overview: string;
  concepts: string[];
  prerequisites: string[];
  learningObjectives: string[];
}

/**
 * AI-generated study notes
 */
export interface AIStudyNotes {
  notes: string;
  keyTakeaways: string[];
  practiceQuestions?: string[];
}
